# QMSS 301 Web Scarping - Reddit

In [1]:
# This part is to import the packages for later analysis. 
import requests
import pandas as pd

# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

# **API Security Tokens**

In [2]:
# This part is to pass login method, user name and passowrd 
auth = requests.auth.HTTPBasicAuth('FUieF7xEkLsimc79KGxSjA', 'uuiREkQQT0HknLLNCMHp8j_l8j4Byw')

data = {'grant_type': 'password',
        'username': 'Lucky_Race_4947',
        'password': '@Lyx990621.'}

In [3]:
# This part is to setup header info, which gives reddit a brief description of our app
headers = {'User-Agent': 'MyBot/0.0.1'}

# This is to send  request for an OAuth token
res = requests.post('https://www.reddit.com/api/v1/access_token',
                    auth=auth, data=data, headers=headers)

# This is to convert response to JSON and pull access_token value
TOKEN = res.json()['access_token']

# This is to add authorization to our headers dictionary
headers = {**headers, **{'Authorization': f"bearer {TOKEN}"}}

# **Subreddit Page Details**

In [4]:
# This is to make a request for the trending posts in /r/Health

subreddit = "health"  # subreddit page title - Eg - 
type_post = "best"  # controversial, best, hot, new, random, rising, top
limit = 100   # default: 25; Max: 100
num_pages = 70 # number of pages

# **API Call - Simple Example**

In [ ]:
# This is to extract at least 5000+ posts
response = requests.get(f"https://oauth.reddit.com/r/{subreddit}/{type_post}.json?limit={limit}".format(subreddit, type_post, limit),  
                   headers=headers)

print(response.json()['data']['children'])

**Understanding the Reddit Data**

https://jsonformatter.curiousconcept.com/

# **API Call - Pagination**

**The response will contain an "after" value which you can pass in the next request.**

In [6]:
# This is pagination
url = f"https://oauth.reddit.com/r/{subreddit}/{type_post}.json?limit={limit}".format(subreddit, type_post, limit)
posts = []
after = '' # Default/Initial value
before = '' # Default/Initial value

for page in range(0, num_pages): 
    page_url = url
    if before:
        page_url += '&before=' + before  # before key for the before page (P - 1) -> P is the current page
    if after:
        page_url += '&after=' + after  # after key for the next page (P + 1)
    
    response = requests.get(page_url, headers=headers).json()
    posts += response['data']['children']
    after = response['data']['after']  # Extracting the after field from JSON Data
    before = response['data']['before']  # Extracting the before field from JSON Data

# **Reddit JSON Data Keys**

In [8]:
# This is to printing all the variable keys in the data and have a better understnading of the data structure 
for key in response['data']['children'][0]['data'].keys():
    print(key)

approved_at_utc
subreddit
selftext
author_fullname
saved
mod_reason_title
gilded
clicked
title
link_flair_richtext
subreddit_name_prefixed
hidden
pwls
link_flair_css_class
downs
thumbnail_height
top_awarded_type
hide_score
name
quarantine
link_flair_text_color
upvote_ratio
author_flair_background_color
subreddit_type
ups
total_awards_received
media_embed
thumbnail_width
author_flair_template_id
is_original_content
user_reports
secure_media
is_reddit_media_domain
is_meta
category
secure_media_embed
link_flair_text
can_mod_post
score
approved_by
is_created_from_ads_ui
author_premium
thumbnail
edited
author_flair_css_class
author_flair_richtext
gildings
post_hint
content_categories
is_self
mod_note
created
link_flair_type
wls
removed_by_category
banned_by
author_flair_type
domain
allow_live_comments
selftext_html
likes
suggested_sort
banned_at_utc
url_overridden_by_dest
view_count
archived
no_follow
is_crosspostable
pinned
over_18
preview
all_awardings
awarders
media_only
can_gild
spoiler
locked
author_flair_text
treatment_tags
visited
removed_by
num_reports
distinguished
subreddit_id
author_is_blocked
mod_reason_by
removal_reason
link_flair_background_color
id
is_robot_indexable
report_reasons
author
discussion_type
num_comments
send_replies
whitelist_status
contest_mode
mod_reports
author_patreon_flair
author_flair_text_color
permalink
parent_whitelist_status
stickied
url
subreddit_subscribers
created_utc
num_crossposts
media
is_video

# **JSON Data Array to Pandas Dataframe**

In [11]:
# This is to initialize the data frmae and append the data points into the datafromae 
df = pd.DataFrame()  

for post in posts:
    df = df.append({
        'subreddit': post['data']['subreddit'],
        'title': post['data']['title'],
        'selftext': post['data']['selftext'],
        'upvote_ratio': post['data']['upvote_ratio'], 
        'ups': post['data']['ups'],
        'downs': post['data']['downs'],
        'score': post['data']['score'],
        'total_awards_received': post['data']['total_awards_received'], 
        'num_comments': post['data']['num_comments'],
        'name': post ['data']['name']
    }, ignore_index=True)

df.head()

,subreddit,title,selftext,upvote_ratio,ups,downs,score,total_awards_received,num_comments,name
0,Health,9 million children to be vaccinated against po...,,0.97,227,0,227,1,9,t3_tm4duo
1,Health,Male birth control pill 99 per cent effective ...,,0.77,9,0,9,0,1,t3_tmvnpp
2,Health,FDA: Unsanitary Conditions Found at Baby Food ...,,1.00,8,0,8,0,1,t3_tmqs4n
3,Health,California governor signs law that makes abort...,,0.95,791,0,791,0,20,t3_tkwola
4,Health,Federal judge sides with 12 disabled kids seek...,,0.88,6,0,6,0,0,t3_tmvkjk

# **Saving the data**

In [ ]:
# This is to save the data into a csv file 
df.to_csv('./data1.csv', index=True, header=True)

# **Importing Python Packages**

In [ ]:
# Import necessary packages 
%matplotlib inline
import pandas as pd
import numpy as np
import re
import nltk
from textblob import TextBlob
nltk.download('words')
words = set(nltk.corpus.words.words())
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stop_words = set(stopwords.words('english'))

# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

[nltk_data] Downloading package words to
[nltk_data]     /Users/fuchunyang/nltk_data...
[nltk_data]   Package words is already up-to-date!

# **Importing Data**

In [ ]:
# import the data saved from the r/health subreddit 
df = pd.read_csv('data1.csv') 
df.head()

,Unnamed: 0,subreddit,title,selftext,upvote_ratio,ups,downs,score,total_awards_received,num_comments,name
0,0,Health,9 million children to be vaccinated against po...,NaN,0.97,227,0,227,1,9,t3_tm4duo
1,1,Health,Male birth control pill 99 per cent effective ...,NaN,0.77,9,0,9,0,1,t3_tmvnpp
2,2,Health,FDA: Unsanitary Conditions Found at Baby Food ...,NaN,1.00,8,0,8,0,1,t3_tmqs4n
3,3,Health,California governor signs law that makes abort...,NaN,0.95,791,0,791,0,20,t3_tkwola
4,4,Health,Federal judge sides with 12 disabled kids seek...,NaN,0.88,6,0,6,0,0,t3_tmvkjk

In [ ]:
# Dimension of the dataset
df.shape

(6473, 11)

# **Removing unnecessary columns**

In [ ]:
# Remove the first column that shows "subreddit"
n_df = df.drop(columns = ['subreddit'], axis = 1)
n_df = n_df.drop(n_df.columns[0], axis=1) 
n_df.head()

,title,selftext,upvote_ratio,ups,downs,score,total_awards_received,num_comments,name
0,9 million children to be vaccinated against po...,NaN,0.97,227,0,227,1,9,t3_tm4duo
1,Male birth control pill 99 per cent effective ...,NaN,0.77,9,0,9,0,1,t3_tmvnpp
2,FDA: Unsanitary Conditions Found at Baby Food ...,NaN,1.00,8,0,8,0,1,t3_tmqs4n
3,California governor signs law that makes abort...,NaN,0.95,791,0,791,0,20,t3_tkwola
4,Federal judge sides with 12 disabled kids seek...,NaN,0.88,6,0,6,0,0,t3_tmvkjk

# **Data Pre-Processing: Removal of symbols, URLS, etc.**

In [ ]:
# remove the hashtags 
n_df['title'] = n_df['title'].str.replace("[^a-zA-Z#]", " ")
n_df['title'].head()

0      million children to be vaccinated against po...
1    Male birth control pill    per cent effective ...
2    FDA  Unsanitary Conditions Found at Baby Food ...
3    California governor signs law that makes abort...
4    Federal judge sides with    disabled kids seek...
Name: title, dtype: object

In [ ]:
# title text cleaning; remove several uncessary things such as @, http links, hashtags, etc. This will prepare the data to be ready for sentiment analysis
def clean_title(temp):
    temp = str(temp).lower()
    temp = re.sub("'", "", str(temp)) # to avoid removing contractions in english
    temp = re.sub("@[A-Za-z0-9_]+","", str(temp)) # Removing @mentions
    temp = re.sub("#[A-Za-z0-9_]+","", str(temp)) # Removing # hashtags
    temp = re.sub(r"www.\S+", "", temp) # Removing weblinks
    temp = re.sub(r"http\S+", "", temp)  # Removing http weblinks
    temp = re.sub('[()!?]', ' ', temp) # Removing special symbols
    temp = re.sub('\[.*?\]',' ', temp)
    temp = re.sub("[^a-z0-9]"," ", temp)
    temp = temp.split()
    stopwords = stop_words
    temp = [w for w in temp if not w in stopwords]
    temp = " ".join(word for word in temp)
    return temp

n_df['title'] = n_df['title'].map(lambda x: clean_title(x))
n_df['selftext'] = n_df['selftext'].map(lambda x: clean_title(x))
n_df['title_selftext'] = n_df['title'].astype(str) + "  " + n_df['selftext']
n_df.head()

,title,selftext,upvote_ratio,ups,downs,score,total_awards_received,num_comments,name,title_selftext
0,million children vaccinated polio africa,nan,0.97,227,0,227,1,9,t3_tm4duo,million children vaccinated polio africa nan
1,male birth control pill per cent effective mic...,nan,0.77,9,0,9,0,1,t3_tmvnpp,male birth control pill per cent effective mic...
2,fda unsanitary conditions found baby food factory,nan,1.00,8,0,8,0,1,t3_tmqs4n,fda unsanitary conditions found baby food fact...
3,california governor signs law makes abortions ...,nan,0.95,791,0,791,0,20,t3_tkwola,california governor signs law makes abortions ...
4,federal judge sides disabled kids seeking mask...,nan,0.88,6,0,6,0,0,t3_tmvkjk,federal judge sides disabled kids seeking mask...

In [ ]:
# remove short words less than three letters 
n_df['title'] = n_df['title'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
n_df['selftext'] = n_df['selftext'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
n_df['title_selftext'] = n_df['title_selftext'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

# **Tokenization**

In [ ]:
# separate the whole title sentence into different words so we can do the sentiment analysis about each word 
n_df['tokenized_titles'] = n_df['title'].apply(lambda x: x.split())
n_df['tokenized_titles'].head()

0       [million, children, vaccinated, polio, africa]
1    [male, birth, control, pill, cent, effective, ...
2    [unsanitary, conditions, found, baby, food, fa...
3    [california, governor, signs, makes, abortions...
4    [federal, judge, sides, disabled, kids, seekin...
Name: tokenized_titles, dtype: object

In [ ]:
# separate the whole selftext sentence into different words so we can do the sentiment analysis about each word 
n_df['tokenized_selftext'] = n_df['selftext'].apply(lambda x: x.split())
n_df['tokenized_selftext'].head()

0    []
1    []
2    []
3    []
4    []
Name: tokenized_selftext, dtype: object

In [ ]:
# separate the combination of title and selftext into different words so we can do the sentiment analysis about each word 
n_df['tokenized_title_selftext'] = n_df['title_selftext'].apply(lambda x: x.split())
n_df['tokenized_title_selftext'].head()

0       [million, children, vaccinated, polio, africa]
1    [male, birth, control, pill, cent, effective, ...
2    [unsanitary, conditions, found, baby, food, fa...
3    [california, governor, signs, makes, abortions...
4    [federal, judge, sides, disabled, kids, seekin...
Name: tokenized_title_selftext, dtype: object

# **Stemming**

In [ ]:
# Implementing the stemming procedure; Stemming is a rule-based process of stripping the suffixes (“ing”, “ly”, “es”, “s” etc) from a word. 
# For example “play”, “player”, “played”, “plays” and “playing” are the different variations of the word – “play”.
stemmer = PorterStemmer()
tokenized_titles = n_df['tokenized_titles'].apply(lambda x: [stemmer.stem(i) for i in x]) # stemming
n_df['tokenized_titles']= tokenized_titles
n_df.head()

,title,selftext,upvote_ratio,ups,downs,score,total_awards_received,num_comments,name,title_selftext,tokenized_titles,tokenized_selftext,tokenized_title_selftext
0,million children vaccinated polio africa,,0.97,227,0,227,1,9,t3_tm4duo,million children vaccinated polio africa,"[million, children, vaccin, polio, africa]",[],"[million, children, vaccinated, polio, africa]"
1,male birth control pill cent effective mice tr...,,0.77,9,0,9,0,1,t3_tmvnpp,male birth control pill cent effective mice tr...,"[male, birth, control, pill, cent, effect, mic...",[],"[male, birth, control, pill, cent, effective, ..."
2,unsanitary conditions found baby food factory,,1.00,8,0,8,0,1,t3_tmqs4n,unsanitary conditions found baby food factory,"[unsanitari, condit, found, babi, food, factori]",[],"[unsanitary, conditions, found, baby, food, fa..."
3,california governor signs makes abortions cheaper,,0.95,791,0,791,0,20,t3_tkwola,california governor signs makes abortions cheaper,"[california, governor, sign, make, abort, chea...",[],"[california, governor, signs, makes, abortions..."
4,federal judge sides disabled kids seeking mask...,,0.88,6,0,6,0,0,t3_tmvkjk,federal judge sides disabled kids seeking mask...,"[feder, judg, side, disabl, kid, seek, mask, s...",[],"[federal, judge, sides, disabled, kids, seekin..."

In [ ]:
# Implementing the stemming procedure for selftext 
stemmer = PorterStemmer()
tokenized_selftext = n_df['tokenized_selftext'].apply(lambda x: [stemmer.stem(i) for i in x]) # stemming
n_df['tokenized_selftext']= tokenized_selftext
n_df.head()

,title,selftext,upvote_ratio,ups,downs,score,total_awards_received,num_comments,name,title_selftext,tokenized_titles,tokenized_selftext,tokenized_title_selftext
0,million children vaccinated polio africa,,0.97,227,0,227,1,9,t3_tm4duo,million children vaccinated polio africa,"[million, children, vaccin, polio, africa]",[],"[million, children, vaccinated, polio, africa]"
1,male birth control pill cent effective mice tr...,,0.77,9,0,9,0,1,t3_tmvnpp,male birth control pill cent effective mice tr...,"[male, birth, control, pill, cent, effect, mic...",[],"[male, birth, control, pill, cent, effective, ..."
2,unsanitary conditions found baby food factory,,1.00,8,0,8,0,1,t3_tmqs4n,unsanitary conditions found baby food factory,"[unsanitari, condit, found, babi, food, factori]",[],"[unsanitary, conditions, found, baby, food, fa..."
3,california governor signs makes abortions cheaper,,0.95,791,0,791,0,20,t3_tkwola,california governor signs makes abortions cheaper,"[california, governor, sign, make, abort, chea...",[],"[california, governor, signs, makes, abortions..."
4,federal judge sides disabled kids seeking mask...,,0.88,6,0,6,0,0,t3_tmvkjk,federal judge sides disabled kids seeking mask...,"[feder, judg, side, disabl, kid, seek, mask, s...",[],"[federal, judge, sides, disabled, kids, seekin..."

In [ ]:
# Implementing the stemming procedure for the combination of title and selftext 
stemmer = PorterStemmer()
tokenized_title_selftext = n_df['tokenized_title_selftext'].apply(lambda x: [stemmer.stem(i) for i in x]) # stemming
n_df['tokenized_title_selftext']= tokenized_title_selftext
n_df.head()

,title,selftext,upvote_ratio,ups,downs,score,total_awards_received,num_comments,name,title_selftext,tokenized_titles,tokenized_selftext,tokenized_title_selftext
0,million children vaccinated polio africa,,0.97,227,0,227,1,9,t3_tm4duo,million children vaccinated polio africa,"[million, children, vaccin, polio, africa]",[],"[million, children, vaccin, polio, africa]"
1,male birth control pill cent effective mice tr...,,0.77,9,0,9,0,1,t3_tmvnpp,male birth control pill cent effective mice tr...,"[male, birth, control, pill, cent, effect, mic...",[],"[male, birth, control, pill, cent, effect, mic..."
2,unsanitary conditions found baby food factory,,1.00,8,0,8,0,1,t3_tmqs4n,unsanitary conditions found baby food factory,"[unsanitari, condit, found, babi, food, factori]",[],"[unsanitari, condit, found, babi, food, factori]"
3,california governor signs makes abortions cheaper,,0.95,791,0,791,0,20,t3_tkwola,california governor signs makes abortions cheaper,"[california, governor, sign, make, abort, chea...",[],"[california, governor, sign, make, abort, chea..."
4,federal judge sides disabled kids seeking mask...,,0.88,6,0,6,0,0,t3_tmvkjk,federal judge sides disabled kids seeking mask...,"[feder, judg, side, disabl, kid, seek, mask, s...",[],"[feder, judg, side, disabl, kid, seek, mask, s..."

# **Text Classification using TextBlob**

The sentiment function of textblob returns two properties, polarity, and subjectivity. Polarity is float which lies in the range of [-1,1] where 1 means positive statement and -1 means a negative statement.


Subjective sentences generally refer to personal opinion, emotion or judgment whereas objective refers to factual information. Subjectivity is also a float which lies in the range of [0,1].

In [ ]:
# Creating columns with the result of the sentiment text analysis for title 
n_df['polarity_t'] = n_df['title'].apply(lambda x: TextBlob(x).sentiment.polarity)
n_df['subjectivity_t'] = n_df['title'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
n_df[['title', 'polarity_t', 'subjectivity_t']].head()

,title,polarity_t,subjectivity_t
0,million children vaccinated polio africa,0.0,0.00
1,male birth control pill cent effective mice tr...,0.3,0.45
2,unsanitary conditions found baby food factory,0.0,0.00
3,california governor signs makes abortions cheaper,0.0,0.00
4,federal judge sides disabled kids seeking mask...,-0.2,0.30

In [ ]:
# Creating columns with the result of the sentiment text analysis for selftext  
n_df['polarity_s'] = n_df['selftext'].apply(lambda x: TextBlob(x).sentiment.polarity)
n_df['subjectivity_s'] = n_df['selftext'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
n_df[['selftext', 'polarity_s', 'subjectivity_s']].head()

  selftext  polarity_s  subjectivity_s
0                  0.0             0.0
1                  0.0             0.0
2                  0.0             0.0
3                  0.0             0.0
4                  0.0             0.0

In [ ]:
# Creating columns with the result of the sentiment text analysis for combination of title and selftext 
n_df['polarity_ts'] = n_df['title_selftext'].apply(lambda x: TextBlob(x).sentiment.polarity)
n_df['subjectivity_ts'] = n_df['title_selftext'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
n_df[['title_selftext', 'polarity_ts', 'subjectivity_ts']].head()

,title_selftext,polarity_ts,subjectivity_ts
0,million children vaccinated polio africa,0.0,0.00
1,male birth control pill cent effective mice tr...,0.3,0.45
2,unsanitary conditions found baby food factory,0.0,0.00
3,california governor signs makes abortions cheaper,0.0,0.00
4,federal judge sides disabled kids seeking mask...,-0.2,0.30

# **Sentiment Analysis using Polarity**

In [ ]:
# Utility function to classify the polarity of the title of a post using textblob.
def analyze_sentiment(title):
    '''
    Utility function to classify the polarity of a Reddit post
    using textblob.
    '''
    analysis = TextBlob(clean_title(title))
    if analysis.sentiment.polarity > 0:
        return 1 # Positive
    elif analysis.sentiment.polarity == 0:
        return 0 # Neutral
    else:
        return -1 # Negative

In [ ]:
# Utility function to classify the polarity of the selftext of a post using textblob.
def analyze_sentiment(selftext):
    '''
    Utility function to classify the polarity of a Reddit post
    using textblob.
    '''
    analysis = TextBlob(clean_title(selftext))
    if analysis.sentiment.polarity > 0:
        return 1 # Positive
    elif analysis.sentiment.polarity == 0:
        return 0 # Neutral
    else:
        return -1 # Negative

In [ ]:
# Utility function to classify the polarity of the combination of selftext and title of a post using textblob.
def analyze_sentiment(title_selftext):
    '''
    Utility function to classify the polarity of a Reddit post
    using textblob.
    '''
    analysis = TextBlob(clean_title(title_selftext))
    if analysis.sentiment.polarity > 0:
        return 1 # Positive
    elif analysis.sentiment.polarity == 0:
        return 0 # Neutral
    else:
        return -1 # Negative

In [ ]:
# Creating a sentiment column with the result of the analysis for title 
n_df['sentiment_t'] = np.array([ analyze_sentiment(title) for title in n_df['title'] ])
n_df[['title', 'sentiment_t']].head()

                                               title  sentiment_t
0           million children vaccinated polio africa            0
1  male birth control pill cent effective mice tr...            1
2      unsanitary conditions found baby food factory            0
3  california governor signs makes abortions cheaper            0
4  federal judge sides disabled kids seeking mask...           -1

In [ ]:
# Creating a sentiment column with the result of the analysis for selftext 
n_df['sentiment_s'] = np.array([ analyze_sentiment(title) for title in n_df['selftext'] ])
n_df[['selftext', 'sentiment_s']].head()

  selftext  sentiment_s
0                     0
1                     0
2                     0
3                     0
4                     0

In [ ]:
# Creating a sentiment column with the result of the analysis for the combination of title and selftext 
n_df['sentiment_ts'] = np.array([ analyze_sentiment(title) for title in n_df['title_selftext'] ])
n_df[['title_selftext', 'sentiment_ts']].head()

                                      title_selftext  sentiment_ts
0           million children vaccinated polio africa             0
1  male birth control pill cent effective mice tr...             1
2      unsanitary conditions found baby food factory             0
3  california governor signs makes abortions cheaper             0
4  federal judge sides disabled kids seeking mask...            -1

In [ ]:
# Converting the values into string texts
n_df['sentiment_title'] = n_df.sentiment_t.map({1: "Positive", 0:"Neutral", -1:"Negative"})
n_df[['title', 'sentiment_t', 'sentiment_title']].head()

,title,sentiment_t,sentiment_title
0,million children vaccinated polio africa,0,Neutral
1,male birth control pill cent effective mice tr...,1,Positive
2,unsanitary conditions found baby food factory,0,Neutral
3,california governor signs makes abortions cheaper,0,Neutral
4,federal judge sides disabled kids seeking mask...,-1,Negative

In [ ]:
# Converting the values into string texts
n_df['sentiment_selftext'] = n_df.sentiment_s.map({1: "Positive", 0:"Neutral", -1:"Negative"})
n_df[['selftext', 'sentiment_s', 'sentiment_selftext']].head()

  selftext  sentiment_s sentiment_selftext
0                     0            Neutral
1                     0            Neutral
2                     0            Neutral
3                     0            Neutral
4                     0            Neutral

In [ ]:
# Converting the values into string texts
n_df['sentiment_title_selftext'] = n_df.sentiment_ts.map({1: "Positive", 0:"Neutral", -1:"Negative"})
n_df[['title_selftext', 'sentiment_ts', 'sentiment_title_selftext']].head()

,title_selftext,sentiment_ts,sentiment_title_selftext
0,million children vaccinated polio africa,0,Neutral
1,male birth control pill cent effective mice tr...,1,Positive
2,unsanitary conditions found baby food factory,0,Neutral
3,california governor signs makes abortions cheaper,0,Neutral
4,federal judge sides disabled kids seeking mask...,-1,Negative

# **Export CSV**

In [ ]:
# Exporting the results into PDF
n_df.to_csv('./sentiment_data.csv', index=True, header=True)